### ISSUE TITLE
Please support carbon tags

### ISSUE THREAD

**Issue by bzed** [lomik/carbon-clickhouse#10]
Since 1.1.0 carbon supports metric tags:
http://graphite.readthedocs.io/en/latest/tags.html#

Please support them in carbon-clickhouse! I think storing tags in a carbon compatible way in redis would be the easiest option. Storing them in clickhouse would require graphite-clickhouse to provide a http tag finder service, which should also not be too hard to implement.

I'm happy to help with the coding.

Thanks,
Bernd

**Comment by lomik** [comment]
I'm studying the implementation of tags in graphite-web/carbon. It's very bad.

But I have not yet got to the point of how it works with the CLUSTER_SERVERS.

**Comment by deniszh** [comment]
>But I have not yet got to the point of how it works with the CLUSTER_SERVERS.

All servers in the cluster share same TagDB instance?

**Comment by lomik** [comment]
{quote}All servers in the cluster share same TagDB instance?{quote}
graphite-web itself searches for a series of tag and sends a request for each backend to each series? I can't believe this

**Comment by deniszh** [comment]
@lomik:
If we talking about `carbon`, i.e. writing - [task is quite simple](https://graphite.readthedocs.io/en/latest/tags.html#carbon):
"Carbon will automatically decode the tags, normalize the tag order, and register the series in the tag database." 
But CLUSTER_SERVERS is part of graphite_web. So, for reading it's doing [exactly that](https://graphite.readthedocs.io/en/latest/tags.html#querying) - [seriesByTag calling tagdb.find_series() ](https://github.com/graphite-project/graphite-web/blob/506f499b5e5b153212b7954b9fd2cdd4ae9431e4/webapp/graphite/render/evaluator.py#L148-L154),  [tagdb.find_series() caching results of tagdb._find_series()](https://github.com/graphite-project/graphite-web/blob/dabbf02ee58984dcc5aafb8fb0c9c2a14686beb5/webapp/graphite/tags/base.py#L19-L64), which is [run query for specific TagDB](https://github.com/graphite-project/graphite-web/search?utf8=%E2%9C%93&q=_find_series&type=) to get list of metrics by tag.

**Comment by deniszh** [comment]
I.e. both `carbon` and `graphite-web` just share single instance of TagDB service, which can be part of graphite-web, or [separate service](https://github.com/grafana/metrictank/pull/750)

**Comment by lomik** [comment]
Experiment result:

I created 2 series:
```
:/# echo "hello.world;host=localhost;service=bash 41 1511200882" | nc -q0 graphite 2003
:/# echo "hello.world;host=localhost;service=foobar 42 1511200882" | nc -q0 graphite 2003
```
then I called seriesByTag from graphite-web with CLUSTER_SERVERS
```
/render/?width=586&height=308&target=seriesByTag("host=~local*")
```

Backend received this request
```
GET /render/?format=pickle&local=1&noCache=1&from=1511115346&until=1511201746&target=hello.world%3Bhost%3Dlocalhost%3Bservice%3Dbash&target=hello.world%3Bhost%3Dlocalhost%3Bservice%3Dfoobar&now=1511201746
```
Graphite-web found series and fetch them in single request with multiple "target".

Overall need to implement for tag support:
* Receive and "normalize" tagged series, put them into "graphite" table. Call graphite-web on new series (it is hard to detect new series)
* Support multiple "target" param in graphite-clickhouse

**Comment by lomik** [comment]
Behavior is changed in graphite-web 1.1.0-rc. seriesByTag filter is passing to CLUSTER_SERVER
```
/render/?format=pickle&local=1&noCache=1&from=1513155287&until=1513241687&target=seriesByTag%28%27host%3Dlocalhost%27%29&now=1513241687
```

**Comment by deniszh** [comment]
Please also note that `graphite-clickhouse` (and probably `go-carbon` too) doesn't work with graphite-web 1.1.x because of multiple `target` params. :(
Will try to make a patch.

**Comment by nikita-b** [comment]
@lomik Hi! 1.0.1 version was released. Do you plan to add support for tags? Thanks!

**Comment by deniszh** [comment]
Just wanted to note that in current implementation 3rd party tags support can be difficult. Implementing tags store in carbon-clickhouse is relatively easy, but rendering support is much harder. Probably it's easier to write special finder for that or change Graphite-web to not propagate tag calls to backends if HTTP TAGDB is used (then you'll need centralized TagDB storage, but that's a different story).

**Comment by lomik** [comment]
> Please also note that graphite-clickhouse (and probably go-carbon too) doesn't work with graphite-web 1.1.x because of multiple target params. :(

Multiple target params support was added into master branch of graphite-clickhouse

**Comment by lomik** [comment]
At the moment, tags are supported by carbon-clickhouse (in master) and by graphite-clickhouse (in master):
* carbon-clickhouse can receive tagged graphite series and write them to table with type `points` in urlencoded format
* carbon-clickhouse can write new table with type `tagged`. See description in README.md
* graphite-clickhouse can use `tagged` table for handle seriesByTag requests

Not yet supported:
* tags autocomplete

**Comment by lomik** [comment]
Now tags autocomplete is also supported in graphite-clickhouse master
