### ISSUE TITLE
Quick Question above Clickhouse Storage Growth

### ISSUE THREAD

**Issue by beegmon** [lomik/carbon-clickhouse#12]
Hello,

I recently deployed this and its working great. I am so glad to be moving away from worrying about whisper files exploding!!!

However, I have a quick question.

Since clickhouse doesn't support something like a TTL (at least yet). How is space growth in the DB managed over time. Is this handled by the defined Rollup?

**Comment by lomik** [comment]
Rollup rules can't remove old data. You should delete them manually using ALTER TABLE DROP PARTITION

**Comment by beegmon** [comment]
Yeah I did more reading last night and refreshed my memory on how clickhouse works, and came to the same conclusion. Sorry for the noise, should have dug around more before asking.

Thanks for getting back to me though!
