### ISSUE TITLE
0.11.3+ goes to 100% cpu usage

### ISSUE THREAD

**Issue by Hipska** [lomik/carbon-clickhouse#122]
I'm using quite the default configuration as in the README.md file and noticed that as of version 0.11.3, carbon-clickhouse goes to 100% cpu usage and no errors or warnings appear in the log file.

The last stable version seems to be 0.11.2 where cpu usage goes to <1%.

**Comment by lexx-bright** [comment]
Also noticed this. Raised after 22e83d224d44b6748bedfa078bf478f8982c3a60

**Comment by msaf1980** [comment]
I'll plann revert in PR #123 after some testing

**Comment by msaf1980** [comment]
Can you test current master ? As I see, no high CPU usage at idle. If worked as expected, I'll release fixed version.

**Comment by lexx-bright** [comment]
Can confirm the issue is fixed on the current master.

**Comment by msaf1980** [comment]
New version (0.11.5) with fix is released
