### ISSUE TITLE
Clickhouse-client instead of HTTP?

### ISSUE THREAD

**Issue by ei-grad** [lomik/carbon-clickhouse#15]
Did someone test the clickhouse-client batch mode for inserting data? I guess it should give a better perfomance... carbon-clickhouse already got pretty much for good perfomance and IMO the current bottleneck should be somewhere in HTTP stack :).

**Comment by lomik** [comment]
Now carbon-clickhouse can save 2+ mln points per second over http interface. Are you really need more? 
PS. I haven't test clickhouse-cli vs http
