### ISSUE TITLE
Does carbon-clickhouse aggregate values before storing them  n clickhouse

### ISSUE THREAD

**Issue by agend** [lomik/carbon-clickhouse#24]
I have configured to send metric every second, but noticed that all data is kinda sparse -  points every 5 minutes! May mis-reconfigured something?
Example of raw data which comes to the clickhouse-graphite:
```
10_5_7_57.cpu.all 2.437 1537884024
10_5_7_57.cpu.all 2.831 1537884025
```

How they appears in clickhouse
```
─Path────────────┬──Value─┬───────Time─┬───────Date─┬──Timestamp
│ 10_5_7_57.cpu.all │ 77.388 │ 1537878900 │ 2018-09-25 │ 1537890323 │
│ 10_5_7_57.cpu.all │ 65.251 │ 1537879200 │ 2018-09-25 │ 1537890323 │
│ 10_5_7_57.cpu.all │ 77.209 │ 1537879500 │ 2018-09-25 │ 1537890581 │
```

In DB all timestamp is 5 minutes discrete.

Could be a problem with data conversion?

**Comment by lomik** [comment]
carbon-clickhouse doesn't aggregate anything. Check you relay (statsd or something else) if exists and rollup rules in clickhouse.

**Comment by agend** [comment]
Thank you @lomik . Issue was in rollup scheme.
