### ISSUE TITLE
Support for timestamp as -1

### ISSUE THREAD

**Issue by agend** [lomik/carbon-clickhouse#25]
Hi
  We use `-1` as value for  timestamp (it is valid according to https://graphite.readthedocs.io/en/latest/feeding-carbon.html ) but carbon-clickhouse set it to 4294967295 (max value for uint32). 
  I have checked https://github.com/lomik/carbon-clickhouse/blob/master/receiver/plain.go#L77 and in case of `-1` it will overflow when conversion to `uint32` will be performed.
  Should I prepare MR?

**Comment by lomik** [comment]
> Should I prepare MR?

I don't mind :)

**Comment by agend** [comment]
@lomik  Will you release version any time soon?)

**Comment by lomik** [comment]
> @lomik Will you release version any time soon?)

Not yet planned. Too few changes from previous release.
