### ISSUE TITLE
Best way to send data into cluster

### ISSUE THREAD

**Issue by ralphM78** [lomik/carbon-clickhouse#28]
Hi,

I have a question about the best way how to send data into a cluster. Maybe someone has expirinses .
Lets say there is a 4 node cluster with carbon-clickhouse and clickhouse with replication configured. In front of that a relay is placed. What is the performantest way to send data in ?
With consistent-hash ring and clickhouse will replicate tables or sending all data to all nodes ?
Hopefully my question is unterstandable.

**Comment by ralphM78** [comment]
For newbies it's hard to understand clickhouse but now I think, I have understood it.

**Comment by Hipska** [comment]
Could you (for newbies) also elaborate a little? I am wondering the same thing right now..

**Comment by ralphM78** [comment]
No idea if it's the best solution but for me it works. 
Lets say you have two servers in a cluster. One shard per server . On both servers a database "mydatabase" with table "mytable" exists. Then you can create a distributed table, "default.mytable" for example, over these tables on both nodes. Simply write into these distributed tables. Data will be distributed over the shards. 

I send metrics into a 4 node cluster with carbon-c-relay (cluster type any_of).

Hope that helps.
