### ISSUE TITLE
Can't parse path from metric with colons (prometheus)

### ISSUE THREAD

**Issue by flyik** [lomik/carbon-clickhouse#34]
```package main

import (
	"fmt"
	"net/url"
)

func main() {
	// fail
	u, _ := url.Parse("instance:cpu_utilization:ratio_avg?dc=qwe&fqdn=asd&instance=10.33.10.10%3A9100&job=node")
	fmt.Printf("Path is '%s' \n", u.Path)

	// success
	r, _ := url.Parse("test_metric?dc=qwe&fqdn=asd&instance=10.33.10.10%3A9100&job=node")
	fmt.Printf("Path 2 is '%s' \n", r.Path)
}


>>>
Path is '' 
Path 2 is 'test_metric' 
```

https://github.com/lomik/carbon-clickhouse/blob/master/uploader/tagged.go#L71
Tag1 becomes just `__name__` and graphite-clickhouse can't find any metrics with this name.

Can it be fixed somehow?

**Comment by lomik** [comment]
https://prometheus.io/docs/instrumenting/writing_exporters/#naming

> Exposed metrics should not contain colons, these are reserved for user defined recording rules to use when aggregating.

**Comment by flyik** [comment]
Didn't see that. Sorry for disturbing

**Comment by lomik** [comment]
I will support metric with colons anyway

**Comment by lomik** [comment]
fixed in master
