### ISSUE TITLE
Performance metrics?

### ISSUE THREAD

**Issue by spoofedpacket** [lomik/carbon-clickhouse#35]
Does carbon-clickhouse have any equivalent to the internal carbon-cache PPU/update operations/update time metrics? Or is this something that's better exposed by clickhouse itself?

Context: I'm evaluating carbon-clickhouse in comparison to traditional python-carbon + whisper. It appears to be accepting a very high volume of metrics without issue but I'm interested in how it's performing under the hood.

**Comment by lomik** [comment]
carbon-clickhouse uses disk queue for batch upload to clickhouse. The most useful metric - `carbon.agents.*.upload.*.unhandled`. This is lag in seconds between receiving a point and when it starts to appear on the graphs, if you use the default `chunk-interval="1s"`

**Comment by spoofedpacket** [comment]
Brilliant, thanks!
