### ISSUE TITLE
clickhouse merges slower than inserts

### ISSUE THREAD

**Issue by wetnun** [lomik/carbon-clickhouse#36]
So the carbon-clickhouse server seems to be working ok, but I constantly run into the "Merges are processing significantly slower than inserts" errors in click house and I'm wondering if I'm tuning carbon-clickhouse wrong.  I mean I can keep bumping the merge_tree settings in clickhouse, but that feels wrong.  Currently using:

chunk-interval = "5s"
chunk-auto-interval = "10:20s,40:60s"

Which seems to buffer stuff ok, but I'm not even close to full load yet (14 metrics per host * every minute * currently ~100 hosts).  Eventually it will be thousands of hosts and probably more metrics.  Currently I have to keep it at least this in clickhouse:

    <merge_tree>
        <parts_to_delay_insert>600</parts_to_delay_insert>
        <parts_to_throw_insert>120000</parts_to_throw_insert>
        <max_delay_to_insert>100</max_delay_to_insert>
        <max_suspicious_broken_parts>5</max_suspicious_broken_parts>
    </merge_tree>

Any ideas would be great since I'm using the suggested table layout.  Thanks.

**Comment by wetnun** [comment]
What I've been finding from other issues and docs (like https://clickhouse.yandex/docs/en/introduction/performance/#performance-when-inserting-data) is that my carbon-clickhouse doesn't seem to be creating big enough batches and is in stead doing one insert per client connection.  Is it expecting for me to have another layer in front of it to pool the inserts?  that kind of defeats the purpose of using this in the first place.

**Comment by lomik** [comment]
Check the data on the disk (by default in /data/carbon-clickhouse/). Each file is one insert. With your settings (chunk-auto-interval), if files accumulate, they should become larger and appear less often.

Check also the logs of the clickhouse-server. Perhaps there are merge errors

**Comment by blind-oracle** [comment]
@wetnun My setup works fine on a single CH server with default merge settings and `chunk-interval = 5s` with 1.8 million metrics per minute (~35k per second) without any noticeable load on Clickhouse. I estimate it can take 10-20x more load or so.

Maybe you have weird hardware\software or heavy compression on columns. Post your `CREATE TABLE` here if they're not default.

**Comment by wetnun** [comment]
I have a three node cluster for clickhouse (I'm planning on keeping metrics for a while).  And yes, it seems like maybe the issue is now clickhouse.  Came back this morning to clickhouse-server consuming all cores and not returning selects (although I think it's inserting).  What version of clickhouse server is considered "stable"?  I've seen references to the latest install not always being bug free.

As per tables:
```
-- create tables on all nodes
CREATE TABLE default.graphite_local (Path String, Value Float64, Time UInt32, Date Date, Timestamp UInt32) ENGINE = GraphiteMergeTree('graphite_rollup') ORDER BY (Path, Time) SETTINGS index_granularity = 8192
CREATE TABLE default.graphite_index_local (Date Date, Level UInt32, Path String, Version UInt32) ENGINE = ReplacingMergeTree(Version) PARTITION BY toYYYYMM(Date) ORDER BY (Level, Path, Date) SETTINGS index_granularity = 8192

-- create distributed on primary only
CREATE TABLE default.graphite_index (Date Date, Level UInt32, Path String, Version UInt32) ENGINE = Distributed(metrics_3shard_1rep, default, graphite_index_local, rand())
CREATE TABLE default.graphite (Path String, Value Float64, Time UInt32, Date Date, Timestamp UInt32) ENGINE = Distributed(metrics_3shard_1rep, default, graphite_local, rand())
```

When clickhouse-server starts freaking out I'm getting these errors, but only when the server is being weird:

```
2019.06.03 12:15:42.537878 [ 99 ] {c489ba25-b21b-4148-b64a-b43336010835} <Information> HTTPHandler: Done processing query
2019.06.03 12:15:42.540265 [ 74 ] {d33acae9-7354-4ca9-baae-ee7d236d37d6} <Information> default.graphite_local (Data): Delaying inserting block by 10.2588 ms. because there are 24744 parts
2019.06.03 12:15:42.551359 [ 74 ] {d33acae9-7354-4ca9-baae-ee7d236d37d6} <Information> executeQuery: Read 14 rows, 673.00 B in 0.014 sec., 1011 rows/sec., 47.49 KiB/sec.
2019.06.03 12:15:42.551488 [ 74 ] {d33acae9-7354-4ca9-baae-ee7d236d37d6} <Information> HTTPHandler: Done processing query
2019.06.03 12:15:42.590695 [ 18 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 10, e.displayText() = DB::Exception: Not found column Version in block. There are only columns: Path, Value, Time, Date, Timestamp, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x68d1bf6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x3174fbf]
2. clickhouse-server(DB::Block::getPositionByName(std::string const&) const+0xde) [0x5de13de]
3. clickhouse-server(DB::GraphiteRollupSortedBlockInputStream::GraphiteRollupSortedBlockInputStream(std::vector<std::shared_ptr<DB::IBlockInputStream>, std::allocator<std::shared_ptr<DB::IBlockInputStream> > > const&, std::vector<DB::SortColumnDescription, std::allocator<DB::SortColumnDescription> > const&, unsigned long, DB::Graphite::Params const&, long)+0x5ba) [0x63b48ca]
4. clickhouse-server(DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, DB::MergeListEntry&, long, DB::DiskSpaceMonitor::Reservation*, bool)+0x26f9) [0x61fdd39]
5. clickhouse-server(DB::StorageMergeTree::merge(bool, std::string const&, bool, bool, std::string*)+0x35b) [0x614ecab]
6. clickhouse-server(DB::StorageMergeTree::backgroundTask()+0x168) [0x61506a8]
7. clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x3e8) [0x61b1538]
8. clickhouse-server() [0x61b1f34]
9. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x187) [0x68d7947]
10. clickhouse-server() [0x745371f]
11. /lib64/libpthread.so.0(+0x7dd5) [0x7fa856d03dd5]
12. /lib64/libc.so.6(clone+0x6d) [0x7fa856005ead]
 (version 19.6.2.1)
```

The rollup and parts still seems off.  Still feels wrong to have bumped the parts_to_throw_insert so high.  As per the temp files, it seems like it rotates them very fast.  Here is a log file I generated using `watch -n 1 "ls -lh /opt/carbon-clickhouse/ | tee -a /tmp/carbon-clickhouse-tmp.log"` over a minute or something.

https://gist.github.com/wetnun/9185ae7e05e0b515dfb84e2ef595adfa

Interesting point, if I have a graph (like `carbon.agents.${main_box}.tcp.*`), it always works, but my other graphs for that three node cluster fail to load because it can' get the data back (6+ metrics per graph).  The metrics all show up in the form of `vm${vmId}.${thing}.${metric}` which should be fine, I always do system ID first out of habit for hashing from older systems.

Is there maybe an example somewhere of multi-node graphite setup?  Found quite a few docs, but very few working examples of larger systems (honestly, this isn't large).  But short of maybe how carbon-clickhouse fetches data from clickhouse, it's starting to look like more of a clickhouse issue than anything.

**Comment by blind-oracle** [comment]
> What version of clickhouse server is considered "stable"? I've seen references to the latest install not always being bug free.

I'm using latest in 19.5 branch. Current 'stable' is of course not much stable, so don't run for bleeding edge.

> When clickhouse-server starts freaking out I'm getting these errors, but only when the server is being weird

Well an error says it all. For some time Clickhouse docs were wrong about GraphiteMergeTree settings - they stated it requires `Version` column but the CH was actually using `Timestamp`. Probably in 19.6 they fixed this. So recreate your tables with `Version` instead of `Timestamp` or downgrade to 19.5

**Comment by wetnun** [comment]
Hmm, I'll try changing versions of the server then.  I have been using the Altinity repo (running Centos7), but I see there is also https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/.  Which only goes up to 19.4 under stable oddly enough.  But looks like the Altinity repo has the older versions, I'll try grabbing one of those.

**Comment by blind-oracle** [comment]
You can also just change

```
<graphite_rollup>
 <version_column_name>Version</version_column_name>
</graphite_rollup>
```

Then the merges will succeed and you shouldn't get any errors.

**Comment by lomik** [comment]
> Probably in 19.6 they fixed this. 

As far as i see it unchanged in source code https://github.com/yandex/ClickHouse/blob/db6de83fa1e16e7a5062ee2c3e31d273c186f550/dbms/src/Storages/MergeTree/registerStorageMergeTree.cpp#L173

Most likely the version_column_name=Version is specified somewhere in the config.

**Comment by wetnun** [comment]
So I rolled everything back to clickhouse-server-19.5.4.22 and updated the config.xml rollup to use Timestamp instead of Version, so far it's running right now.  I guess time will tell if that was the main issue or not.  Thanks for the help.

**Comment by blind-oracle** [comment]
Why wait, use `SELECT * FROM system.merges` to see current merges and `SELECT * FROM system.parts WHERE table = 'graphite'` to see if your parts are merged or not.

**Comment by wetnun** [comment]
Totally forgot to follow up, sorry.  So it's been running super smooth since the downgrade.  Thanks for the help.

**Comment by blind-oracle** [comment]
>  So it's been running super smooth since the downgrade

It would certainly run as well with a newer version and changed config, so don't hesitate to upgrade if needed :)

**Comment by benwtr** [comment]
@wetnun `rand()` as a sharding key on a distributed table that sends inserts to a graphite table is going to “break” rollup. (I’m assuming that’s what you’re doing but maybe you are handling inserts some other way, in which case ignore me)

Rollup happens on the local graphite table in each shard, it has no awareness of the distributed table. Multiple shards (if not all) will have points for any given metric within a range when performing rollup. Usually this means you end up with as many shards as you have * the amount of data you expected the rollup rule to leave you with. 

One way you can solve this is to shard on `modulo(intHash64(Path), number_of_shards)` so that a Path always inserts to the same shard.

**Comment by wetnun** [comment]
Hmm, that seems logical.  I've had it running for a while now but I haven't dug into the disk space usage (of which it hasn't been much).  I was actually meaning to lookup how to do consistent hashing like that on insert.  I was just concerned about having it be off of something dumb like a timestamp which is just an oscillating firehose of data.  But on `Path` I think it would work fine.

The puppet report collector I run on the same head (which I'm thinking of trying to integrate into Clickhouse somehow) is actually more of a system stress at the moment.
