### ISSUE TITLE
Ограничение на размер вставки в clickhouse

### ISSUE THREAD

**Issue by newsett1er** [lomik/carbon-clickhouse#38]
Под высокой нагрузкой создаёт файлы буфера превышающие возможность вставки. Приводит к потере значений. Было бы полезно иметь ограничение на размер вставки.
Пример:
[upload] handle failed {"name": "graphite", "filename": "/data/carbon-clickhouse/graphite/default.1560255814879835735", "error": "clickhouse response status 500: Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 966.00 MiB (attempt to allocate chunk of 16777216 bytes), maximum: 953.67 MiB (version 19.5.3.8 (official build))\n", "time": 0.791713384}

**Comment by lomik** [comment]
Кажется достаточно сделать ограничение на размер чанка в байтах. Сейчас оно только в секундах.
Сделаю в ближайшем будущем

**Comment by newsett1er** [comment]
Да, хороший выход.
