### ISSUE TITLE
unable to find metrics sent trough prometheus

### ISSUE THREAD

**Issue by butlerx** [lomik/carbon-clickhouse#39]
Im unable to find metrics that are written by Prometheus endpoint.

I can see that it is receiving metrics from `carbon.agent.*.prometheus.samplesRecieved`  but I'm unable to query for any metrics

**Comment by lomik** [comment]
Where you search them?

Metrics from Prometheus are accessible using [seriesByTag function](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.seriesByTag)

**Comment by butlerx** [comment]
the query im using is `seriesByTag('job=prometheus_master')`
and my response is ```
Object
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/120/render"
data:"target=seriesByTag('job%3Dprometheus_master')&from=-30d&until=now&format=json&maxDataPoints=2353"
response:Array[0]
```

**Comment by butlerx** [comment]
this appears to possibly be an issue with both my backends `carbonapi` and `graphite-web-1.0.2`. will update graphite-web to version higher than `1.1.1`

**Comment by deniszh** [comment]
@butlerx: `seriesByTag` was introduced in `graphite-web` v1.1.1, indeed.
And it exists currently only in `master` branch of [carbonapi](https://github.com/go-graphite/carbonapi).

**Comment by butlerx** [comment]
carbonapi master shows are metrics thanks
