### ISSUE TITLE
Provide logrotate config

### ISSUE THREAD

**Issue by Hipska** [lomik/carbon-clickhouse#42]
Hi,

It would be nice if the package also provides a logrotate config, as with the default settings, the log file can become quite big very quickly.

This is my suggestion:
```logrotate
/var/log/carbon-clickhouse/carbon-clickhouse.log {
    compress
    delaycompress
    copytruncate
    notifempty
    rotate 30
    daily
}
```

**Comment by Hipska** [comment]
@lomik what do you think?

**Comment by Felixoid** [comment]
From my personal experience, it's difficult to find some decent defaults for everybody. But, maybe, bad defaults, in any case, better than nothing.
