### ISSUE TITLE
Create a public repository for easy updating.

### ISSUE THREAD

**Issue by beliys** [lomik/carbon-clickhouse#43]
Create a public repository for easy updating. Now deb/rpm packages are created, but they need to be installed manually, which is not very convenient. As option there is service cloudsmith.io, which allows you to create free repositories without any restrictions for Open-Source projects (https://cloudsmith.io/f/open_source/). The service has its own API for easy automatic interaction.
I think it would make it easier to install and update your services for systems without docker.

**Comment by lomik** [comment]
Why not. I will try to do this

**Comment by Hipska** [comment]
You could also use packagecloud.io like the guy of [carbonapi](https://github.com/go-graphite/carbonapi) is doing: https://packagecloud.io/go-graphite/

**Comment by Hipska** [comment]
Hi @lomik, just saw You released a new version, did you have time to look into this?

**Comment by lomik** [comment]
I spent some time studying the "ubuntu ppa" repositories. Maintaining such a repository takes too much effort. Probably have to use the packagecloud or something like it :(

**Comment by Hipska** [comment]
Indeed, maintaining a repo completely is waste of time and overkill. Something like packagecloud only requires you to upload the packages and that’s it.

**Comment by lskillen** [comment]
@cloudsmith-io is just as easy btw (thanks to @beliys for the mention), and we're always on hand to give advice and support if needed. :-) If you're open-source you don't need to apply for it, just create an open-source repository and off you go!

**Comment by lomik** [comment]
Packages were uploaded to packagecloud https://packagecloud.io/go-graphite/stable . graphite-clickhouse packages will be uploaded later

**Comment by beliys** [comment]
Thanks, updated from the repository
