### ISSUE TITLE
rewrite-rules.conf

### ISSUE THREAD

**Issue by AlexFinn** [lomik/carbon-clickhouse#44]
Есть ли возможность использовать что-то вроде `rewrite-rules.conf` для изменения имени метрики?

**Comment by lomik** [comment]
Такой возможности нет. Предполагается что это можно сделать на стороне балансировщика/агрегатора. Например, carbon-c-relay или carbon-relay-ng

**Comment by AlexFinn** [comment]
спасибо :) попробую на стороне carbon-c-relay сделать
