### ISSUE TITLE
Telegraf HTTP JSON receiver combines the measurement and field with an underscore

### ISSUE THREAD

**Issue by Hipska** [lomik/carbon-clickhouse#46]
It seems that when using Telegraf HTTP JSON receiver, the measurement name and field name are combined with an underscore. When configuring Telefgraf to send data as graphite output to `carbon-clickhouse`, they are combined with a dot. The dot is in my opinion also more logical.

I use the http transport as it seems smaller in size when compared to the graphite transport. (especially when using tags a lot)

**Comment by lomik** [comment]
I'm trying to maintain naming compatibility with Prometheus. Dot is disallowed in Prometheus

**Comment by Hipska** [comment]
We are talking about graphite, no?

Could you please make this configurable then?

**Comment by lomik** [comment]
> We are talking about graphite, no?
carbon-clickhouse, graphite-clickhouse can be used as long term storage for Prometheus. Moreover graphite-clickhouse has a built-in Prometheus web interface and can be used in Grafana as data source with prometheus protocol.

> Could you please make this configurable then?
I don't mind. PR are welcome

**Comment by Hipska** [comment]
I'm sorry, I don't have much to zero experience with Go. Don't know where to start.

**Comment by Hipska** [comment]
@lomik I tried to implement this with a config option, but got lost on how or where I should pick on. Everything seems to be extracted away so much. Could you give me any pointers please?

**Comment by Hipska** [comment]
I think I found a solution (#83), let me know what you think of it.
