### ISSUE TITLE
Pickl receiver

### ISSUE THREAD

**Issue by bzed** [lomik/carbon-clickhouse#5]
Hi,

please implement a pickle receiver for carbon-clickhouse. Pickle reduces a lot of the network overhead we are seeing.

Thanks for your awesome work,

Bernd

**Comment by lomik** [comment]
I thought no one is using it :) He is incompatible with carbon-c-relay and other graphite load balancers

**Comment by bzed** [comment]
carbon-relay-ng works well with pickle. I've replaced carbon-c-relay with it as the grafana dashboard for carbon-relay-ng is really helpful to spot bottlenecks easily.

**Comment by lomik** [comment]
Pickle support has been added in version 0.4
