### ISSUE TITLE
shard metrics across tables

### ISSUE THREAD

**Issue by matthew-hollick** [lomik/carbon-clickhouse#50]
Hi,

I have been looking at the feature of graphite-clickhouse where you can define which table is to be used to fetch metrics from as defined by a regex.
Carbon-clickhouse allows multiple data tables to be written to but in my testing it appears that it is only possible to send all the metrics to all the tables.

Is there a way, or do you plan to implement a way, to filter which metrics go to which tables in a manner similar to how graphite-clickhouse already queries for them?

Regards,

Matthew.

**Comment by lomik** [comment]
Hi,

Regex in graphite-clickhouse can filter only targets (not metrics). This allows you to send particularly heavy queries to separate tables (with a different retention or materialized view).

I don't have plan to implement sharding inside carbon-clickhouse. Try to use external relay (carbon-c-relay etc)

**Comment by matthew-hollick** [comment]
Thanks for the answer :-)
