### ISSUE TITLE
Question about the "Time" column

### ISSUE THREAD

**Issue by spoofedpacket** [lomik/carbon-clickhouse#56]
I have a quick question about the purpose of the "Time" column in the graphite clickhouse database. Does it record the time the metric was received by carbon-clickhouse?

**Comment by Hipska** [comment]
It records the the time that was sent as the metric time.

**Comment by Felixoid** [comment]
Hey, here's a description of the GraphiteMergeTree data table https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/graphitemergetree/#creating-table
